name: Rebuild Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Test runner
        run: |
          echo "HELLO"
          uname -a
          id
          pwd

      - uses: actions/checkout@v6

      - name: Build the Docker image
        run: |
          echo "Starting make"
          make
          echo "make returned successfully"
